import { useState } from "react";
import { CheckCircle2, Clock3, Edit3, Loader2, MapPin, Plus, Power, Trash2, X } from "lucide-react";
import ConfirmDialog from "@/components/ui/ConfirmDialog";
import { useToast } from "@/lib/providers/ToastProvider";
import { useSaveShippingZones, useShippingSettings, type ShippingZone } from "@/lib/api/queries";

const emptyZone: ShippingZone = { code: "", name: "", description: "", rate: 0, minDeliveryDays: 1, maxDeliveryDays: 3, active: true, sortOrder: 1 };
const money = (value: number, currency = "USD") => new Intl.NumberFormat("en-US", { style: "currency", currency }).format(value);

export default function ShippingZonesPage() {
  const toast = useToast();
  const { data, isLoading, isError, refetch } = useShippingSettings();
  const saveZones = useSaveShippingZones();
  const [draft, setDraft] = useState<ShippingZone | null>(null);
  const [originalCode, setOriginalCode] = useState<string | null>(null);
  const [deleting, setDeleting] = useState<ShippingZone | null>(null);
  const zones = data?.zones ?? [];

  function openZone(zone?: ShippingZone) { setOriginalCode(zone?.code ?? null); setDraft(zone ? { ...zone } : { ...emptyZone, sortOrder: zones.length + 1 }); }
  async function persist(nextZones: ShippingZone[], message: string) {
    try { await saveZones.mutateAsync({ zones: nextZones }); setDraft(null); setDeleting(null); toast.success(message); }
    catch (error) { toast.error("Shipping zones were not saved", error instanceof Error ? error.message : "Please try again."); }
  }
  function saveDraft() {
    if (!draft) return;
    if (!draft.name.trim() || !draft.code.trim()) return toast.error("Name and code are required");
    if (draft.maxDeliveryDays < draft.minDeliveryDays) return toast.error("Invalid delivery range", "Maximum days must be greater than or equal to minimum days.");
    const next = originalCode ? zones.map((zone) => zone.code === originalCode ? draft : zone) : [...zones, draft];
    persist(next, originalCode ? "Shipping zone updated" : "Shipping zone added");
  }
  function toggle(zone: ShippingZone) {
    if (zone.active && zones.filter((item) => item.active).length === 1) return toast.error("One active zone is required");
    persist(zones.map((item) => item.code === zone.code ? { ...item, active: !item.active } : item), zone.active ? "Shipping zone disabled" : "Shipping zone enabled");
  }

  return <div className="mx-auto max-w-[1400px] space-y-6">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-2 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.16em] text-slate-500"><MapPin className="h-4 w-4" />Shipping configuration</div><h1 className="text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">Shipping zones</h1><p className="mt-2 text-sm text-slate-500">Configure the options, prices, and delivery estimates customers see at checkout.</p></div><button type="button" onClick={() => openZone()} className="action-primary"><Plus className="h-4 w-4" />Add zone</button></header>
    {isLoading ? <div className="h-64 animate-pulse rounded-2xl bg-slate-200" /> : isError ? <ErrorState onRetry={() => refetch()} /> : <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left"><thead className="bg-slate-50 text-[11px] font-bold uppercase tracking-wider text-slate-500"><tr><th className="px-5 py-3">Delivery zone</th><th className="px-5 py-3">Checkout code</th><th className="px-5 py-3">Charge</th><th className="px-5 py-3">Estimate</th><th className="px-5 py-3">Status</th><th className="px-5 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{zones.map((zone) => <tr key={zone.code} className="hover:bg-slate-50/70"><td className="px-5 py-4"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-950 text-white"><MapPin className="h-4 w-4" /></span><div><p className="text-sm font-bold text-slate-900">{zone.name}</p><p className="mt-1 max-w-[280px] truncate text-xs text-slate-400">{zone.description || "No description"}</p></div></div></td><td className="px-5 py-4"><code className="rounded-md bg-slate-100 px-2 py-1 text-xs text-slate-600">{zone.code}</code></td><td className="px-5 py-4 text-sm font-bold text-slate-950">{money(zone.rate, data?.currency)}</td><td className="px-5 py-4"><p className="flex items-center gap-1.5 text-sm text-slate-700"><Clock3 className="h-4 w-4 text-slate-400" />{zone.minDeliveryDays}–{zone.maxDeliveryDays} business days</p></td><td className="px-5 py-4"><button type="button" onClick={() => toggle(zone)} disabled={saveZones.isPending} className={zone.active ? "status-active" : "rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-500"}><Power className="h-3 w-3" />{zone.active ? "Active" : "Disabled"}</button></td><td className="px-5 py-4"><div className="flex justify-end gap-1"><button type="button" onClick={() => openZone(zone)} className="icon-button" aria-label={`Edit ${zone.name}`}><Edit3 className="h-4 w-4" /></button><button type="button" onClick={() => setDeleting(zone)} className="icon-button text-rose-600" aria-label={`Delete ${zone.name}`}><Trash2 className="h-4 w-4" /></button></div></td></tr>)}</tbody></table></div><footer className="border-t border-slate-100 px-5 py-4 text-xs text-slate-400">Zone changes are applied to new checkout sessions and do not modify existing orders.</footer></section>}
    {draft && <Editor title={originalCode ? "Edit shipping zone" : "Add shipping zone"} saving={saveZones.isPending} onClose={() => setDraft(null)} onSave={saveDraft}><div className="grid gap-4 sm:grid-cols-2"><Field label="Zone name" required><input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} className="field" placeholder="Inside Dhaka" /></Field><Field label="Unique code" required><input value={draft.code} onChange={(event) => setDraft({ ...draft, code: event.target.value.toLowerCase().replace(/[^a-z0-9-]/g, "-") })} className="field" placeholder="dhaka" disabled={Boolean(originalCode)} /></Field><div className="sm:col-span-2"><Field label="Customer-facing description"><input value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} className="field" placeholder="Dhaka metropolitan area" /></Field></div><Field label={`Delivery charge (${data?.currency ?? "USD"})`} required><input type="number" min="0" step="0.01" value={draft.rate} onChange={(event) => setDraft({ ...draft, rate: Number(event.target.value) })} className="field" /></Field><Field label="Display order"><input type="number" min="0" value={draft.sortOrder} onChange={(event) => setDraft({ ...draft, sortOrder: Number(event.target.value) })} className="field" /></Field><Field label="Minimum delivery days" required><input type="number" min="0" max="90" value={draft.minDeliveryDays} onChange={(event) => setDraft({ ...draft, minDeliveryDays: Number(event.target.value) })} className="field" /></Field><Field label="Maximum delivery days" required><input type="number" min="0" max="90" value={draft.maxDeliveryDays} onChange={(event) => setDraft({ ...draft, maxDeliveryDays: Number(event.target.value) })} className="field" /></Field><label className="sm:col-span-2 flex items-center justify-between rounded-xl border border-slate-200 bg-slate-50 p-4"><span><span className="block text-sm font-semibold text-slate-800">Available at checkout</span><span className="mt-1 block text-xs text-slate-500">Customers can select this delivery zone.</span></span><input type="checkbox" checked={draft.active} onChange={(event) => setDraft({ ...draft, active: event.target.checked })} className="h-5 w-5 accent-slate-950" /></label></div></Editor>}
    <ConfirmDialog open={Boolean(deleting)} title="Delete shipping zone?" description={`${deleting?.name ?? "This zone"} will disappear from checkout. Historical orders remain unchanged.`} confirmLabel="Delete zone" tone="danger" loading={saveZones.isPending} onCancel={() => setDeleting(null)} onConfirm={() => deleting && persist(zones.filter((zone) => zone.code !== deleting.code), "Shipping zone deleted")} />
  </div>;
}

function Editor({ title, saving, onClose, onSave, children }: { title: string; saving: boolean; onClose: () => void; onSave: () => void; children: React.ReactNode }) { return <div className="fixed inset-0 z-[80] flex items-end justify-center bg-slate-950/50 p-0 backdrop-blur-sm sm:items-center sm:p-4"><div className="w-full max-w-2xl rounded-t-2xl bg-white shadow-2xl sm:rounded-2xl"><header className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><h2 className="font-bold text-slate-950">{title}</h2><button type="button" onClick={onClose} className="icon-button"><X className="h-4 w-4" /></button></header><div className="max-h-[70vh] overflow-y-auto p-5">{children}</div><footer className="flex justify-end gap-2 border-t border-slate-100 p-4"><button type="button" onClick={onClose} className="action-secondary">Cancel</button><button type="button" onClick={onSave} disabled={saving} className="action-primary">{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : <CheckCircle2 className="h-4 w-4" />}Save zone</button></footer></div></div>; }
function Field({ label, required, children }: { label: string; required?: boolean; children: React.ReactNode }) { return <label><span className="mb-1.5 block text-xs font-semibold text-slate-600">{label}{required && <span className="text-rose-600"> *</span>}</span>{children}</label>; }
function ErrorState({ onRetry }: { onRetry: () => void }) { return <div className="rounded-2xl border border-rose-200 bg-white p-8 text-center"><p className="font-bold text-slate-950">Shipping zones could not be loaded</p><button type="button" onClick={onRetry} className="mt-4 action-primary">Try again</button></div>; }
